num1=int(input("enter first number"))
num2=float(input("enter second number"))
num3=int(input("enter third number"))
num4=input("enter fourth number")
print(num1 + num2 + num3)
print(num1 + num2 - num3)
print(num1 + num2 / num3)
print(num1 + num2 * num3)
print=(num1 + num4)
